### ISSUE TITLE
The type or namespace name 'LocalizedStringProxy' could not be found

### ISSUE THREAD

**Issue by zjf0123** [TsFreddie/Unity-Localization-ParadoxNotion#1]
Hi! I got such errors when trying to import the package to my project.
![image](https://github.com/TsFreddie/Unity-Localization-ParadoxNotion/assets/46274573/2641323c-3318-4a9c-ba8d-36fd0d977267)
![image](https://github.com/TsFreddie/Unity-Localization-ParadoxNotion/assets/46274573/415796d6-11f2-4122-af85-ff56806f3123)

**Comment by TsFreddie** [comment]
Can you check whether the Editor assembly is correctly imported and being referenced?

**Comment by TsFreddie** [comment]
~~Ah wait, somehow there isnt a Editor assembly definition at all in the repo. Don't know how I missed that.~~

~~You can create one yourself in the Editor folder and reference it. I'll double check the repo in the meantime.~~

**Comment by TsFreddie** [comment]
Oops, sorry for spamming. It's been a while since I've touched this. Looks like the Editor script is actually put in the same assembly. Then my first comment applies, double check whether this Editor folder is there 
<img width="473" alt="image" src="https://github.com/TsFreddie/Unity-Localization-ParadoxNotion/assets/3797859/f37358ae-fc2d-4d55-b650-f096d1644511">
<img width="226" alt="image" src="https://github.com/TsFreddie/Unity-Localization-ParadoxNotion/assets/3797859/14ef7ce6-9315-4e10-8bde-d9ff82ff37d1">

**Comment by zjf0123** [comment]
> Oops, sorry for spamming. It's been a while since I've touched this. Looks like the Editor script is actually put in the same assembly. Then my first comment applies, double check whether this Editor folder is there <img alt="image" width="473" src="https://private-user-images.githubusercontent.com/3797859/301812300-f37358ae-fc2d-4d55-b650-f096d1644511.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzAwNjAsIm5iZiI6MTcwNjg2OTc2MCwicGF0aCI6Ii8zNzk3ODU5LzMwMTgxMjMwMC1mMzczNThhZS1mYzJkLTRkNTUtYjY1MC1mMDk2ZDE2NDQ1MTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTAyOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmRjYTk5YTcyOTY1YzU4NGFiMDMwOTgyOTczMzlkZGI2MWNhMGIxNDc1YjIwNTU5YjU1YzJiY2EzZjgyNmQ0MyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Qfs2yprm8ZX-QtzNUCifyabFo3fG_cf_vDqvYb-Hd-o"> <img alt="image" width="226" src="https://private-user-images.githubusercontent.com/3797859/301812359-14ef7ce6-9315-4e10-8bde-d9ff82ff37d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NzAwNjAsIm5iZiI6MTcwNjg2OTc2MCwicGF0aCI6Ii8zNzk3ODU5LzMwMTgxMjM1OS0xNGVmN2NlNi05MzE1LTRlMTAtOGJkZS1kOWZmODJmZjM3ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDJUMTAyOTIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGZlOGIyMTk1NTdmODAxZGQ0MWVlNDliOTYwNDNhNDVmNzgzODQzZmU3MWU4YzE0MDhmOGMyOGYzNzAwYWY0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c_amA2Toul36L2EPHuphjGPHIcym4gm3OBDKXVM1gk8">

Yes, there is a Editor folder

**Comment by zjf0123** [comment]
![image](https://github.com/TsFreddie/Unity-Localization-ParadoxNotion/assets/46274573/3c610981-dbfd-4a8a-a82b-2b298c449ffb)

**Comment by zjf0123** [comment]
Hi, the problem was fixed after i added this file to my project.
It seems that you forget to pack this file.
![image](https://github.com/TsFreddie/Unity-Localization-ParadoxNotion/assets/46274573/b49f1935-72a6-4342-ae8e-545261718a7b)

**Comment by TsFreddie** [comment]
ye maybe. i'll double check again. thanks
